# ==============================================================================
# Google Cloud Build Configuration for Community Arctic Map
# ==============================================================================
# This file defines the build process for the containerized application
# 
# Usage:
#   gcloud builds submit --config=.deployment/cloudbuild.yaml \
#     --substitutions=_VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN}
# ==============================================================================

options:
  machineType: 'E2_HIGHCPU_8'  # Use higher CPU for faster builds
  logging: CLOUD_LOGGING_ONLY

# Substitution variables (passed from GitHub Actions or command line)
substitutions:
  _REGION: 'us-east1'
  _SERVICE_NAME: 'community-arctic-map'
  _VITE_MAPBOX_ACCESS_TOKEN: ''  # Must be provided
  _VITE_BACKEND_API_URL: ''      # Optional, defaults to relative URLs
  _VITE_DOWNLOAD_API_URL: ''     # Optional, defaults to relative URLs

steps:
  # Step 1: Build the Docker image with build-time environment variables
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--file=.deployment/Dockerfile'
      - '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'
      - '--build-arg=VITE_MAPBOX_ACCESS_TOKEN=${_VITE_MAPBOX_ACCESS_TOKEN}'
      - '--build-arg=VITE_BACKEND_API_URL=${_VITE_BACKEND_API_URL}'
      - '--build-arg=VITE_DOWNLOAD_API_URL=${_VITE_DOWNLOAD_API_URL}'
      - '--cache-from=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}'
    waitFor: ['build-image']

# Images to be pushed (for Cloud Build UI)
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'

# Build timeout (increase if builds take longer)
timeout: '1800s'  # 30 minutes
