# Cloud Build configuration for Arctic Map Application
# This file defines automated build and deployment pipeline for Google Cloud Run
#
# Trigger: Manual via gcloud builds submit or via Cloud Build trigger
#
# Usage:
#   gcloud builds submit --config=.deployment/cloudbuild.yaml

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - '.deployment/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arctic-map:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arctic-map:latest'
      - '.'
    id: 'build-image'
    timeout: '1200s'  # 20 minutes for large image build

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/arctic-map:$SHORT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/arctic-map:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'arctic-map'
      - '--image=gcr.io/$PROJECT_ID/arctic-map:$SHORT_SHA'
      - '--platform=managed'
      - '--region=us-central1'  # Modify region as needed
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-secrets=VITE_MAPBOX_ACCESS_TOKEN=mapbox-access-token:latest,GOOGLE_SHEET_ID=google-sheet-id:latest,GOOGLE_SHEET_GID=google-sheet-gid:latest'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image-sha', 'push-image-latest']

# Store built images
images:
  - 'gcr.io/$PROJECT_ID/arctic-map:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/arctic-map:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'  # Use high-CPU machine for faster builds
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON

# Timeout for entire build
timeout: '2400s'  # 40 minutes total

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'arctic-map'
